[package]
name = "rubble"
description = "a slight blog system"
version = "0.3.1"
authors = ["Kilerd Chan <blove694@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
diesel = { version = "1.3.3", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.9.0"
r2d2 = "0.8"
lazy_static = "1.1"
serde = "1.0"
serde_derive = "1.0"
tera = "0.11.0"
pulldown-cmark = { version = "0.1.2", default-features = false }
chrono = { version = "*", features = ["serde"] }
rust-crypto = "^0.2"

actix-web= "1.0.0-alpha.6"
actix-files = "0.1.0-alpha.6"
actix = "0.8.1"
diesel_migrations = "1.4.0"
futures = "0.1.26"
http = "0.1.17"
rand = "0.6.5"
pretty_env_logger = "0.3.0"
time = "0.1.42"
rss = "1.7.0"
diesel_derives = "1.4.0"
openssl = "0.10.22"
log = "0.4.6"
